name: Create Release

on:
  push:
    branches: ['main']

  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: install dependencies
        run: npm ci
      - name: Build extension
        run: npm run build
      - name: Get version
        id: get_version
        run: |
             TAG=${{ steps.tag_version.outputs.new_tag }}
             echo "VERSION=${TAG#v}" >> "$GITHUB_OUTPUT"
      - name: Update manifest.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: ./build/manifest.json
          field: version
          value: ${{ steps.get_version.outputs.VERSION }}
      - name: Zip Build
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: manhua-check-extension.zip
          directory: ./build
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "./build/manhua-check-extension.zip"
