name: Create Release

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          node-version: 20
          cache: npm
      - name: install dependencies
        run: npm ci
      - name: Build extension
        run: npm run build
      - name: Zip Build
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: release.zip
          directory: ./build
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
    
  
